controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    resource: ../../src/Api/
    type: annotation
    prefix: /api
    name_prefix: api_

kernel:
    resource: ../../src/Kernel.php
    type: annotation
